version: "3"
services:
  stc-app:
    container_name: stc-server
    image: stc-server
    volumes:
      - /home/stc/stc_data:/app/stc_data
    restart: always
    build: .
    ports: 
      - "8001:8001"
    links: 
      - mongo
  mongo:
    environment: 
      - AUTH=no
    container_name: mongo
    image: mongo
    volumes:
      - ./stc_data/db:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command:
      mongod --port 27017 --bind_ip_all

  